---
# tasks file for vector-role
- name: Download Vector
  ansible.builtin.get_url:
    url: "{{ vector_distro.path }}{{ vector_distro.version }}/{{ vector_distro.package }}"
    dest: "/tmp/{{ vector_distro.package }}"
  tags: vector
# установка использует модуль ansible deb
- name: Install Vector package
  ansible.builtin.apt:
    deb: "/tmp/{{ vector_distro.package }}"
  notify: Start Vector service
  tags: vector
# Создание каталога для sources
- name: Creates directory
  become: true
  file:
    path: /var/lib/vector/local_logs
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644
  tags: vector
# Делаем из шаблона конфиг для сервиса
- name: Deploy config Vector
  ansible.builtin.template:
    src: vector.j2
    dest: "{{ vector_config_path }}"
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
  become: true
  notify: Start Vector service
  tags: vector

- name: Create systemd unit Vector
  become: true
  template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  notify: Start Vector service
  tags: vector